spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # DB 스키마 자동 생성
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 pretty print
    show-sql: true # SQL 쿼리 출력
    open-in-view: true
  profiles:
    include: database
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG # 로그 단계 설정
server:
  servlet:
    encoding:
      force-response: true # MockMVC 테스트에서 응답에 한글이 깨지는 현상 해결 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.server.server.servlet.encoding.force-response

jwt:
  key:
    secret: ${JWT_SECRET_KEY_STACK}
  access-token-expiration-minutes: 1051200
  refresh-token-expiration-minutes: 420