spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # DB 스키마 자동 생성
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 pretty print
    show-sql: true # SQL 쿼리 출력
    open-in-view: true
  profiles:
    include: database
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
  port: 9000
mail:
  address:
    admin: admin@gmail.com

jwt:
  key: "c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK"
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420