spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pre-database-1.cguixlvnvxu0.ap-northeast-2.rds.amazonaws.com:3306/pre41?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 54255425
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 pretty print
    show-sql: true # SQL 쿼리 출력
    open-in-view: true
  profiles:
    include: database
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com

config:
  domain: http://pre41-deploy-test.s3-website.ap-northeast-2.amazonaws.com/

jwt:
  key: "c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK"
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
